export const env = {
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "http://localhost:54321",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "local-dev-key",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "local-dev-service-role",
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3001",
  SUPABASE_STORAGE_BUCKET: process.env.SUPABASE_STORAGE_BUCKET ?? "job-assets",
  LEAD_INGEST_API_KEY: process.env.LEAD_INGEST_API_KEY ?? "",
  DEFAULT_ORG_ID: process.env.DEFAULT_ORG_ID ?? "",
  LEAD_INGEST_ALLOWED_ORIGINS: process.env.LEAD_INGEST_ALLOWED_ORIGINS ?? "",
  AUTH_REQUIRED: process.env.AUTH_REQUIRED ?? "0",
  ATTENDANCE_REMINDER_WEBHOOK_URL: process.env.ATTENDANCE_REMINDER_WEBHOOK_URL ?? "",
};
